[project]
name = "tech-jobs-market-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "psycopg>=3.3.2",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.5.0",
]
